-- Schema dump for @gdgjp/sns
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE sns_contributors (
  chapter_id INTEGER NOT NULL,
  user_email TEXT NOT NULL COLLATE NOCASE,
  granted_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (chapter_id, user_email)
);
CREATE TABLE x_accounts (
  id TEXT PRIMARY KEY,
  chapter_id INTEGER NOT NULL,
  x_user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  display_name TEXT NOT NULL,
  profile_image_url TEXT,
  access_token_ciphertext TEXT NOT NULL,
  refresh_token_ciphertext TEXT,
  access_token_expires_at TEXT,
  authorized_by_user_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  revoked_at TEXT,
  UNIQUE (chapter_id, x_user_id)
);
CREATE INDEX x_accounts_chapter_active ON x_accounts(chapter_id, revoked_at);
CREATE TABLE oauth_transactions (
  state TEXT PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('x', 'google_photos')),
  user_id TEXT NOT NULL,
  chapter_id INTEGER,
  code_verifier TEXT NOT NULL,
  return_to TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE posts (
  id TEXT PRIMARY KEY,
  chapter_id INTEGER NOT NULL,
  x_account_id TEXT NOT NULL REFERENCES x_accounts(id),
  text TEXT NOT NULL,
  scheduled_at TEXT NOT NULL,
  condition TEXT NOT NULL CHECK (condition IN ('scheduled', 'photo_required')),
  status TEXT NOT NULL CHECK (status IN ('scheduled', 'waiting_for_photo', 'posting', 'published', 'failed', 'needs_confirmation')),
  created_by_user_id TEXT NOT NULL,
  published_x_post_id TEXT,
  published_at TEXT,
  failure_reason TEXT,
  link_preview_url TEXT,
  link_preview_title TEXT,
  link_preview_description TEXT,
  link_preview_image_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX posts_due ON posts(status, scheduled_at);
CREATE INDEX posts_chapter_schedule ON posts(chapter_id, scheduled_at);
CREATE TABLE post_media (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  r2_key TEXT NOT NULL UNIQUE,
  content_type TEXT NOT NULL,
  byte_size INTEGER NOT NULL,
  alt_text TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL CHECK (sort_order BETWEEN 0 AND 3),
  created_at TEXT NOT NULL,
  UNIQUE (post_id, sort_order)
);
CREATE TABLE post_media_tags (
  post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  x_user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  PRIMARY KEY (post_id, x_user_id)
);
CREATE TABLE post_attempts (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  attempted_at TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('published', 'failed', 'unknown')),
  detail TEXT
);
CREATE TABLE IF NOT EXISTS "user" (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  image TEXT,
  is_admin INTEGER NOT NULL DEFAULT 0,
  oidc_issuer TEXT,
  oidc_subject TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE UNIQUE INDEX user_oidc_identity_idx
  ON "user" (oidc_issuer, oidc_subject);
CREATE TABLE oidc_session (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  issuer TEXT NOT NULL,
  subject TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  id_token TEXT NOT NULL,
  access_token_expires_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX oidc_session_user_idx ON oidc_session (user_id);
CREATE TABLE google_photos_albums (
  id TEXT PRIMARY KEY,
  chapter_id INTEGER NOT NULL UNIQUE,
  album_url TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  poll_interval_minutes INTEGER NOT NULL DEFAULT 5,
  unchanged_poll_count INTEGER NOT NULL DEFAULT 0,
  next_poll_at TEXT NOT NULL,
  last_success_at TEXT,
  last_error TEXT,
  lease_expires_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
, active_run_id TEXT);
CREATE INDEX google_photos_albums_due
  ON google_photos_albums(enabled, next_poll_at);
CREATE TABLE google_photos_media (
  id TEXT PRIMARY KEY,
  album_id TEXT NOT NULL REFERENCES google_photos_albums(id) ON DELETE CASCADE,
  stable_photo_id TEXT NOT NULL,
  r2_key TEXT NOT NULL UNIQUE,
  content_type TEXT NOT NULL,
  byte_size INTEGER NOT NULL,
  source_url TEXT,
  imported_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL, taken_at TEXT, blurhash TEXT,
  UNIQUE (album_id, stable_photo_id)
);
CREATE INDEX google_photos_media_album_imported
  ON google_photos_media(album_id, imported_at DESC);
CREATE TABLE google_photos_snapshot_items (
  album_id TEXT NOT NULL REFERENCES google_photos_albums(id) ON DELETE CASCADE,
  stable_photo_id TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  PRIMARY KEY (album_id, stable_photo_id)
);
CREATE TABLE google_photos_poll_runs (
  id TEXT PRIMARY KEY,
  album_id TEXT NOT NULL REFERENCES google_photos_albums(id) ON DELETE CASCADE,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  outcome TEXT NOT NULL CHECK (outcome IN ('running', 'imported', 'unchanged', 'failed', 'structure_changed')),
  discovered_count INTEGER NOT NULL DEFAULT 0,
  imported_count INTEGER NOT NULL DEFAULT 0,
  duplicate_count INTEGER NOT NULL DEFAULT 0,
  detail TEXT
);
CREATE INDEX google_photos_poll_runs_album_started
  ON google_photos_poll_runs(album_id, started_at DESC);
CREATE INDEX google_photos_media_album_taken
  ON google_photos_media(album_id, taken_at DESC, imported_at DESC);
