-- Schema dump for @gdgjp/stream
-- Generated by scripts/dump-schema.sh from migrations/*.sql; do not edit by hand.

CREATE TABLE IF NOT EXISTS "user" (
  id           TEXT NOT NULL PRIMARY KEY,
  name         TEXT NOT NULL,
  email        TEXT NOT NULL UNIQUE,
  image        TEXT,
  is_admin     INTEGER NOT NULL DEFAULT 0,
  oidc_issuer  TEXT,
  oidc_subject TEXT,
  created_at   INTEGER NOT NULL DEFAULT 0,
  updated_at   INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX user_oidc_identity_idx ON "user" (oidc_issuer, oidc_subject);
CREATE TABLE oidc_session (
  id                      TEXT NOT NULL PRIMARY KEY,
  user_id                 TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  issuer                  TEXT NOT NULL,
  subject                 TEXT NOT NULL,
  access_token            TEXT NOT NULL,
  refresh_token           TEXT,
  id_token                TEXT NOT NULL,
  access_token_expires_at INTEGER NOT NULL,
  expires_at              INTEGER NOT NULL,
  created_at              INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at              INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX oidc_session_user_idx ON oidc_session (user_id);
CREATE TABLE device_models (
  id       TEXT NOT NULL PRIMARY KEY,
  maker    TEXT,
  name     TEXT NOT NULL,
  -- mic | headphone | speaker | mixer | audio_interface | di | wireless_rx
  -- | recorder | camera | switcher | capture | display | computer
  -- | software_broadcast | software_conferencing | blackbox | generic
  category TEXT NOT NULL,
  -- How signal moves between this device's own ports:
  --   matrix      — routing is the (input × bus) matrix stored on the setup
  --   passthrough — every input reaches every same-medium output (DI, blackbox)
  --   none        — inputs and outputs are unrelated (endpoints, conferencing apps)
  internal_routing TEXT NOT NULL DEFAULT 'none'
    CHECK (internal_routing IN ('matrix', 'passthrough', 'none')),
  notes      TEXT,
  created_by TEXT REFERENCES "user"(id) ON DELETE SET NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at INTEGER
, echo_cancels INTEGER NOT NULL DEFAULT 0);
CREATE INDEX device_models_category_idx ON device_models (category);
CREATE TABLE device_model_buses (
  id       TEXT NOT NULL PRIMARY KEY,
  model_id TEXT NOT NULL REFERENCES device_models(id) ON DELETE CASCADE,
  key      TEXT NOT NULL,
  label    TEXT NOT NULL,
  kind     TEXT NOT NULL CHECK (kind IN ('main', 'aux', 'usb', 'monitor', 'sub')),
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (model_id, key)
);
CREATE TABLE device_model_ports (
  id        TEXT NOT NULL PRIMARY KEY,
  model_id  TEXT NOT NULL REFERENCES device_models(id) ON DELETE CASCADE,
  key       TEXT NOT NULL,
  label     TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('in', 'out')),
  -- av = HDMI/SDI carrying both audio and video.
  signal    TEXT NOT NULL
    CHECK (signal IN ('audio_analog', 'audio_digital', 'video', 'av')),
  connector TEXT NOT NULL DEFAULT 'none'
    CHECK (connector IN ('xlr', 'trs', 'ts', 'trs_mini', 'rca', 'hdmi', 'sdi',
                         'usb_b', 'usb_c', 'speakon', 'none')),
  level     TEXT CHECK (level IS NULL OR level IN ('mic', 'line', 'instrument', 'speaker')),
  channels  INTEGER NOT NULL DEFAULT 1 CHECK (channels >= 1),
  -- provides: can supply +48V. requires: needs it. damaged_by: ribbon mics etc.
  phantom   TEXT NOT NULL DEFAULT 'none'
    CHECK (phantom IN ('provides', 'requires', 'damaged_by', 'none')),
  -- Output ports belong to a bus; input ports do not.
  bus_id    TEXT REFERENCES device_model_buses(id) ON DELETE SET NULL,
  sort_order INTEGER NOT NULL DEFAULT 0, couples TEXT
  CHECK (couples IS NULL OR couples IN ('from_space', 'to_space')), expandable INTEGER NOT NULL DEFAULT 0, source_key TEXT, origin INTEGER NOT NULL DEFAULT 0,
  UNIQUE (model_id, key)
);
CREATE INDEX device_model_ports_model_idx ON device_model_ports (model_id);
CREATE TABLE device_model_default_routes (
  model_id   TEXT NOT NULL REFERENCES device_models(id) ON DELETE CASCADE,
  in_port_id TEXT NOT NULL REFERENCES device_model_ports(id) ON DELETE CASCADE,
  bus_id     TEXT NOT NULL REFERENCES device_model_buses(id) ON DELETE CASCADE,
  PRIMARY KEY (model_id, in_port_id, bus_id)
);
CREATE TABLE devices (
  id         TEXT NOT NULL PRIMARY KEY,
  model_id   TEXT NOT NULL REFERENCES device_models(id),
  name       TEXT NOT NULL,
  -- Something that identifies the physical unit on site: sticker colour, asset tag.
  identifier TEXT,
  -- Free-text memo ("東京チャプター備品" / "田中さん私物"). Not an ACL.
  owner_note TEXT,
  created_by TEXT REFERENCES "user"(id) ON DELETE SET NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at INTEGER
);
CREATE INDEX devices_model_idx ON devices (model_id);
CREATE TABLE events (
  id           TEXT NOT NULL PRIMARY KEY,
  title        TEXT NOT NULL,
  starts_at    INTEGER,
  venue        TEXT,
  -- Optional link out to connpass / Meetup / the wiki runbook.
  external_url TEXT,
  created_by   TEXT REFERENCES "user"(id) ON DELETE SET NULL,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at   INTEGER
);
CREATE INDEX events_starts_at_idx ON events (starts_at);
CREATE TABLE event_devices (
  event_id  TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  device_id TEXT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  note      TEXT,
  PRIMARY KEY (event_id, device_id)
);
CREATE INDEX event_devices_device_idx ON event_devices (device_id);
CREATE TABLE setups (
  id         TEXT NOT NULL PRIMARY KEY,
  event_id   TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  -- SetupDoc JSON. Validated by the zod schema in app/lib/av/schema.ts.
  doc        TEXT NOT NULL,
  created_by TEXT REFERENCES "user"(id) ON DELETE SET NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  deleted_at INTEGER
);
CREATE INDEX setups_event_idx ON setups (event_id);
CREATE TABLE setup_revisions (
  id         TEXT NOT NULL PRIMARY KEY,
  setup_id   TEXT NOT NULL REFERENCES setups(id) ON DELETE CASCADE,
  doc        TEXT NOT NULL,
  author_id  TEXT REFERENCES "user"(id) ON DELETE SET NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
);
CREATE INDEX setup_revisions_setup_idx ON setup_revisions (setup_id, created_at);
